name: iglu_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch=1.8.1 
  - torchvision 
  - cudatoolkit=11.1
  - pip:
    - numpy
    - scipy 
    - matplotlib
    - jupyterlab 
    - scikit-learn 
    - gym 
    - ray[rllib]==1.0.1
    - pandas 
    - wandb 
    - moviepy 
    - transformers